### ISSUE TITLE
Can ignore suggestions

### ISSUE THREAD

**Issue by Roiyaru** [Jigsaw-Code/Intra#106]
Hi, a respected developer. Is it possible to add support for normal dns in Intra? Thank you

**Comment by Roiyaru** [comment]
Because there are not many DNS providers that support DNS-over-TLS and DNS-over-HTTPS, such unreasonable requests are made.

**Comment by alterstep** [comment]
Support for dnscrypt, oh, please ❤️

**Comment by bemasc** [comment]
@Roiyaru We're not planning to add support for insecure DNS protocols.  Intra's purpose is to improve DNS protection, and I wouldn't want anyone to get confused by the presence of insecure options.

@alterstep Right now we're focusing on building the best possible support for DNS over HTTPS.  My hope is that we can encourage more servers to support DNS over HTTPS, and get everyone onto the new standard protocols.
