### ISSUE TITLE
Don't show "::1" when the IP is unknown

### ISSUE THREAD

**Issue by bemasc** [Jigsaw-Code/Intra#110]
Currently, in error cases where there is an unknown or not-applicable IP address, it is rendered in the detailed view as "::1", i.e. IPv6 localhost.  This has created significant confusion.  We should properly track unknown IP addresses and show an explicit error message (maybe "N/A") instead.

**Comment by Stafedor** [comment]
Hello @bemasc, can I work on this issue ?

**Comment by bemasc** [comment]
Definitely!  I think the problem is here: https://github.com/Jigsaw-Code/Intra/blob/63b69708f82ed03773ded32e4a18cfaa51db6a9c/Android/app/src/main/java/app/intra/RecyclerAdapter.java#L224

If we couldn't connect to the server, then `serverIp` is `null`.  I thought this would generate an `UnknownHostException`, but it looks like it [returns localhost](https://bugs.openjdk.java.net/browse/JDK-8202139) instead.

**Comment by bemasc** [comment]
@Stafedor, I had a few minutes and decided to try to solve this myself, but I'm happy to find you another project if you're still interested in contributing.

**Comment by Stafedor** [comment]
@bemasc Yeah I am still interested, sorry for not being active with this issue. I was busy so I forgot to work on it. If you have some issue for me in this project I would like to work on it.
