### ISSUE TITLE
Reliable mechanism to test if DNS queries are secured? 

### ISSUE THREAD

**Issue by shaomeng** [Jigsaw-Code/Intra#121]
Hello,

I wanted to ask if there's a reliable mechanism to know that my DNS queries are essentially encrypted, in addition to seeing Intra running background? 

I meant no offense to the Intra team. I had this question because I checked out the Cloudflare DNS blogs and run a test at https://1.1.1.1/help ; this test seems to show that neither DoH nor DoT was in use for me. The attached screenshot shows my result on my Pixel C tablet.
I should note that if I switched DNS server from Google to Cloudflare, it would show that DoT was in use. 

Hope to hear from you soon!

Cheers,
Sam

![screenshot_20181015-193643](https://user-images.githubusercontent.com/814885/46987899-5f378e80-d0b3-11e8-88ed-ad220c9c746f.png)

**Comment by bemasc** [comment]
Hi @shaomeng.  Unfortunately, I think the Cloudflare status page is a bit confusing here.  The "Using DNS over HTTPS (DoH)" and "Using DNS over TLS (DoT)" status indicators only apply to Cloudflare's DNS service.  As you noted, if you switch to cloudflare-dns.com in Intra, the status page correctly indicates that you are connected to Cloudflare DNS using DoH.
