### ISSUE TITLE
Intra not working

### ISSUE THREAD

**Issue by Tanath** [Jigsaw-Code/Intra#167]
DNS doesn't work when I enable Intra. I've tried the 2 built-in settings, adding Google's manually, and adding Quad9's manually. I'm testing by opening new domains in Chrome. I can only load them with Intra disabled.

I enabled `show recent queries` but the stats stay at 0. Intra doesn't seem to be receiving the queries. I set up Firefox to use Quad9's DoH and it works fine.

I'm on Lineage 15.1-20190225 (Android 8.1.0), also tested an earlier release. I have a firewall, but for now it's disabled.

**Comment by cjhenck** [comment]
I haven't experienced anything similar myself, except when I'm on a captive portal.  Does Intra show itself in a connected state when you enable it, or does it give some other error message?

**Comment by Tanath** [comment]
OK, this is weird. It's working now with no intervention or change on my part. I've been poking it occasionally for days without success. I even showed someone several hours ago and since then my phone has sat there untouched. Intra may have updated in the background along with other apps without me noticing though. Perhaps there was a bug fix that helped me.

**Comment by cjhenck** [comment]
We did make a recent change to the networking stack in the latest version, which was released on Monday. Please feel free to re-open the issue if it happens again.

**Comment by Kuwwatguly** [comment]
Çalişan bir server atinda bizde kullanalim intrayi

**Comment by toylykaka** [comment]
intra rabotayet dns nujna

**Comment by Kuwwatguly** [comment]
Dns oklaň onda

**Comment by toylykaka** [comment]
20 m

**Comment by Kuwwatguly** [comment]
Nomer oklasana bratok kompýutera nadip vpn goýup bilern öwretseň

ср, 12 авг. 2020 г., 12:01 toylykaka <notifications@github.com>:

**Comment by Kuwwatguly** [comment]
20 manat dämi

пт, 14 авг. 2020 г., 07:19 toylykaka <notifications@github.com>:
