### ISSUE TITLE
Possibility to add OpenNIC Public Servers

### ISSUE THREAD

**Issue by maninthemiddle01** [Jigsaw-Code/Intra#170]
Hello,
thank you for your nice program. I'd like to have the possibility to add OpenNIC Public Servers, but I can't find the the server-URL. Do you know, if there is the possibility to find them or would it be possible to add an option in Intra to directly set a server with IPv4 IPv6 parameters?

**Comment by bemasc** [comment]
The [DNS Privacy Test servers](https://dnsprivacy.org/wiki/display/DP/DNS+Privacy+Test+Servers) list shows some resolvers that support both DoH and OpenNIC.  You can get the configuration URL [here](https://github.com/curl/curl/wiki/DNS-over-HTTPS#publicly-available-servers) and enter it in the settings.
