### ISSUE TITLE
Need to be added

### ISSUE THREAD

**Issue by tw-e** [Jigsaw-Code/Intra#186]
@bemasc 

1.Can you please increase the "DNS over TLS" function mechanism?

2.Can you please add "quad101 dns" to the built-in list?
https://blog.twnic.net.tw/2018/12/28/1803/
https://blog.twnic.net.tw/2018/07/02/1086/

**Comment by bemasc** [comment]
Intra is focused on DoH; there is no plan to add support for DNS over TLS at this time.

We would be happy to include TWNIC DoH in the Intra resolver list.  To add TWNIC, we will need authoritative links
1. indicating that the service is supported (not temporary or experimental),
2. explaining any kind of filtering or modification it performs, and
3. providing a clear privacy policy for users.

**Comment by tw-e** [comment]
@bemasc 
This official website, you can compare it, thank you!
https://101.101.101.101/index_en.html
