### ISSUE TITLE
Gradle Sync Issue "Could not find org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.31."

### ISSUE THREAD

**Issue by kklyoon** [Jigsaw-Code/Intra#187]
Here is gradle sync Issue when I try sync it.

my Android Studio version is latest one ( 3.4.1 )

and other projects are OK.

I tried to find the solution by googling but couldn't.

Is there anyone can help me?

```
ERROR: Could not find org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.31.
Searched in the following locations:
  - https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.3.31/kotlin-stdlib-jdk8-1.3.31.pom
  - https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.3.31/kotlin-stdlib-jdk8-1.3.31.jar
  - https://maven.fabric.io/public/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.3.31/kotlin-stdlib-jdk8-1.3.31.pom
  - https://maven.fabric.io/public/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.3.31/kotlin-stdlib-jdk8-1.3.31.jar
  - file:/Users/KKL/Documents/workspace/intra/Intra/Android/firebase-repo/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.3.31/kotlin-stdlib-jdk8-1.3.31.pom
  - file:/Users/KKL/Documents/workspace/intra/Intra/Android/firebase-repo/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.3.31/kotlin-stdlib-jdk8-1.3.31.jar
  - file:/Users/KKL/Documents/workspace/intra/Intra/Android/gradle-plugin-repo/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.3.31/kotlin-stdlib-jdk8-1.3.31.pom
  - file:/Users/KKL/Documents/workspace/intra/Intra/Android/gradle-plugin-repo/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.3.31/kotlin-stdlib-jdk8-1.3.31.jar
Required by:
    project : > com.android.tools.build:gradle:3.4.1
    project : > com.android.tools.build:gradle:3.4.1 > com.android.tools.build:builder:3.4.1
    project : > com.android.tools.build:gradle:3.4.1 > com.android.tools.analytics-library:shared:26.4.1
    project : > com.android.tools.build:gradle:3.4.1 > com.android.tools.lint:lint-gradle-api:26.4.1
    project : > com.android.tools.build:gradle:3.4.1 > com.android.tools.build:gradle-api:3.4.1
    project : > com.android.tools.build:gradle:3.4.1 > androidx.databinding:databinding-compiler-common:3.4.1
    project : > com.android.tools.build:gradle:3.4.1 > com.android.tools.build:builder:3.4.1 > com.android.tools:sdk-common:26.4.1
    project : > com.android.tools.build:gradle:3.4.1 > com.android.tools.build:builder:3.4.1 > com.android.tools:common:26.4.1
    project : > com.android.tools.build:gradle:3.4.1 > com.android.tools.build:builder:3.4.1 > com.android.tools.build:manifest-merger:26.4.1
    project : > com.android.tools.build:gradle:3.4.1 > com.android.tools.build:builder:3.4.1 > com.android.tools.analytics-library:tracker:26.4.1
    project : > com.android.tools.build:gradle:3.4.1 > com.android.tools.build:builder:3.4.1 > com.android.tools:sdklib:26.4.1 > com.android.tools:repository:26.4.1
```

**Comment by bemasc** [comment]
It looks like you upgraded the gradle plugin version from 3.4.0 to 3.4.1.  This changes the dependencies.  For security reasons, Intra includes all third-party dependencies directly (e.g. in Android/gradle-plugin-repo/).  Upgrading the gradle plugin requires updating all its dependencies in that directory.

In general, I recommend not changing the gradle plugin version unless you really need to.  Changing the version back to 3.4.0 should solve your problem.  However, if you really need to update the dependencies, you may be able to use scripts/maven_fetch.py to help.

**Comment by kklyoon** [comment]
It's resolved!!! Thank you @bemasc

**Comment by ThaTBaT** [comment]
Hello
I did change version but still getting following error, please help ;(



ERROR: Could not find org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.21.
Searched in the following locations:
  - https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.3.21/kotlin-stdlib-jdk8-1.3.21.pom
  - https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.3.21/kotlin-stdlib-jdk8-1.3.21.jar
  - https://maven.google.com/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.3.21/kotlin-stdlib-jdk8-1.3.21.pom
  - https://maven.google.com/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.3.21/kotlin-stdlib-jdk8-1.3.21.jar
Required by:
    project : > com.android.tools.build:gradle:3.4.0
    project : > com.android.tools.build:gradle:3.4.0 > com.android.tools.build:builder:3.4.0
    project : > com.android.tools.build:gradle:3.4.0 > com.android.tools.analytics-library:shared:26.4.0
    project : > com.android.tools.build:gradle:3.4.0 > com.android.tools.lint:lint-gradle-api:26.4.0
    project : > com.android.tools.build:gradle:3.4.0 > com.android.tools.build:gradle-api:3.4.0
    project : > com.android.tools.build:gradle:3.4.0 > androidx.databinding:databinding-compiler-common:3.4.0
    project : > com.android.tools.build:gradle:3.4.0 > com.android.tools.build:builder:3.4.0 > com.android.tools:sdk-common:26.4.0
    project : > com.android.tools.build:gradle:3.4.0 > com.android.tools.build:builder:3.4.0 > com.android.tools:common:26.4.0
    project : > com.android.tools.build:gradle:3.4.0 > com.android.tools.build:builder:3.4.0 > com.android.tools.build:manifest-merger:26.4.0
    project : > com.android.tools.build:gradle:3.4.0 > com.android.tools.build:builder:3.4.0 > com.android.tools.analytics-library:tracker:26.4.0
    project : > com.android.tools.build:gradle:3.4.0 > com.android.tools.build:builder:3.4.0 > com.android.tools:sdklib:26.4.0 > com.android.tools:repository:26.4.0
