### ISSUE TITLE
Add a toggle in Quick Settings for faster access

### ISSUE THREAD

**Issue by mans82** [Jigsaw-Code/Intra#194]
It would be way more convenient to switch Intra on or off if there was a toggle in Quick Settings for it. Just like what CloudFlare DNS app has implemented:
![Screenshot_20190621-103410](https://user-images.githubusercontent.com/39344547/59901364-3b7dd280-9410-11e9-84d8-e2fcaac5fea8.jpg)

**Comment by Mikaela** [comment]
This would be helpful for me on Android 9 Go when I visit open WLANs which are blocking DoT/853 port (e.g. Helsinki metro) as there I could just touch the tile and my connectivity would work again (for having specified direct IPv4 address in Intra settings).
