### ISSUE TITLE
Adguard DNS

### ISSUE THREAD

**Issue by Ilia1** [Jigsaw-Code/Intra#197]
Add in default setting dns adguard
https://adguard.com/en/adguard-dns/overview.html#instruction

**Comment by cjhenck** [comment]
Thank you for your suggestion.  The [Play Store guidelines](https://play.google.com/about/privacy-security-deception/device-network-abuse/) list "Apps that block or interfere with another app displaying ads" as a violation of their guidelines.  As a result, we won't be able to add any ad blocking DNS providers to the preconfigured list of servers.

**Comment by Ilia1** [comment]
publish the application in https://f-droid.org/ ?
