### ISSUE TITLE
new IPs and hostname for Foundation for Applied Privacy DoH service

### ISSUE THREAD

**Issue by appliedprivacy** [Jigsaw-Code/Intra#246]
These new IPs are valid from 2020-02-15 the old IPs (and hostname) continue to work until 2020-02-19.
old IPs:
37.252.185.229,2a00:63c1:a:229::2
old hostname: https://doh.appliedprivacy.net/query

New IPs
IPv4 address: 93.177.65.183
IPv6 address: 2a03:4000:38:53c::2
new hostname: https://doh.applied-privacy.net/query

Service documentation:
https://applied-privacy.net/services/dns/

Privacy Policy:
https://applied-privacy.net/privacy-policy/

thanks!

**Comment by bemasc** [comment]
FYI, this change is in Intra 1.2.8, which is now fully released.
