### ISSUE TITLE
are IPs in servers.xml optional?

### ISSUE THREAD

**Issue by appliedprivacy** [Jigsaw-Code/Intra#256]
To increase performance and redundancy we added additional servers (new IPs).

- what arguments does the ipsN field in servers.xml take and how is it consumed?
- more specifically:
  - are IPs required? (we noticed the IIJ resolver does not have an IP, does that mean it will use native DNS first to find the IP of the DoH? what if multiple IPs are returned?)
  - if the ipsN field contains multiple IPs, does the order matter or are they selected randomly?
  - can the policy by which IPs are used first be influenced in the servers.xml file?

thanks!

**Comment by appliedprivacy** [comment]
If IPs are optional we would like to switch to DNS based discovery of our resolver IPs, thanks!

**Comment by bemasc** [comment]
Yes, IPs are optional, and we are happy to remove them.  Note that clients will bootstrap using your domain name via insecure DNS if those IPs are unreachable or not functioning correctly, so removing them shouldn't be necessary even if your address might change.

**Comment by appliedprivacy** [comment]
Thanks for that info, that is relevant.
I guess there is still a difference if the IP is removed since that will be always hit first.
How do you choose the IP to connect to when the A/AAAA records return multiple IPs?

**Comment by bemasc** [comment]
> How do you choose the IP to connect to when the A/AAAA records return multiple IPs?
> Do you attempt to connect to the next IP if the first one returns a HTTP 502 error?

Currently, we
* Resolve the domain name in the URL
* Collect the union of the resolved IPs and any hardcoded IPs
* Try those IPs sequentially in random order until one of them connects
* Attempt a DoH query on the connected socket
* If the query succeeds (HTTP 200), mark this IP address as "confirmed", and try it first from now on.
* Otherwise, fail the query and mark no IP address as "confirmed".

Therefore, if some of the IP addresses are returning 502 errors, this will cause some users to have resolution failures for their first few queries, until the client finds a working IP address, at which point errors should stop.

**Comment by appliedprivacy** [comment]
Thanks for this explanation!

One last thing: Is it possible to list multiple domains?

Fore example:
```
  <string name="url4" translatable="false">https://doh.applied-privacy.net/query</string>
  <string name="name4" translatable="false">Foundation for Applied Privacy</string>
  <string name="ips4" translatable="false">doh.applied-privacy.net,doh.appliedprivacy.net</string>
```

If that is the case we would like to use the domains listed in the example, thanks!

**Comment by jirayupiwon8** [comment]
> To increase performance and redundancy we added additional servers (new IPs).
> 
> - what arguments does the ipsN field in servers.xml take and how is it consumed?
> - more specifically:
>   - are IPs required? (we noticed the IIJ resolver does not have an IP, does that mean it will use native DNS first to find the IP of the DoH? what if multiple IPs are returned?)
>   - if the ipsN field contains multiple IPs, does the order matter or are they selected randomly?
>   - can the policy by which IPs are used first be influenced in the servers.xml file?
> 
> thanks!
>

**Comment by bemasc** [comment]
> * what arguments does the ipsN field in servers.xml take and how is it consumed?

It is a list of hosts (i.e. IP addresses or DNS hostnames).

>   * are IPs required?

No

> (we noticed the IIJ resolver does not have an IP, does that mean it will use native DNS first to find the IP of the DoH?

Yes.

> what if multiple IPs are returned?)

Intra will try them all until it finds one that works.

>   * if the ipsN field contains multiple IPs, does the order matter or are they selected randomly?

They are selected randomly.

>   * can the policy by which IPs are used first be influenced in the servers.xml file?

No.
