### ISSUE TITLE
Error: No named parameter with the name 'onRatingChanged'.                 onRatingChanged: (rating) {                 ^^^^^^^^^^^^^^^ ../../../../../Programs/flutter/.pub-cache/hosted/pub.dartlang.org/smooth_star_rating-1.1.0+1/lib/smooth_star_rating.dart:23:3: Context: Found this candidate, but the arguments don't match.   SmoothStarRating({   ^^^^^^^^^^^^^^^^

### ISSUE THREAD

**Issue by EngAddow** [Jigsaw-Code/Intra#268]
Launching lib\main.dart on Android SDK built for x86 in debug mode...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

Compiler message:
../../../../../Programs/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-0.5.3/lib/src/gesture/extended_image_slide_page_route.dart:331:9: Error: No named parameter with the name 'animation'.
        animation: animation,
        ^^^^^^^^^
../../../../../Programs/flutter/packages/flutter/lib/src/cupertino/route.dart:436:3: Context: Found this candidate, but the arguments don't match.
  CupertinoFullscreenDialogTransition({
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Compiler message:
../../../../../Programs/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-0.5.3/lib/src/gesture/extended_image_slide_page_route.dart:331:9: Error: No named parameter with the name 'animation'.
        animation: animation,
        ^^^^^^^^^
../../../../../Programs/flutter/packages/flutter/lib/src/cupertino/route.dart:436:3: Context: Found this candidate, but the arguments don't match.
  CupertinoFullscreenDialogTransition({
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'E:\from F\Programs\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 896
* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'E:\from F\Programs\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 58s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

I have this problem please help me to solve it?

**Comment by bemasc** [comment]
Intra doesn't use Dart or Flutter, so you must have the wrong Github project.
