### ISSUE TITLE
BUG  --  The internet seems to disconnect while the VPN is on after a few moments.

### ISSUE THREAD

**Issue by Cyberdroid1** [Jigsaw-Code/Intra#270]
**BUG**

After I connect to the VPN with the server doh.applied-privacy.net, the interconnection seems to drop even if I am connected to the WiFi or mobile data. And this doesn't happen all the time. Please look into this issue. It is stopping me from using the app properly.

**Comment by captainhook** [comment]
I was seeing the same with my own DoH server, not sure what tests I can carry out but I'm certain it's to do with Intra because DNSCloak on a few iOS devices have shown no problem.

After reinstalling the app, it is not showing this behaviour any more for me. You may want to try reinstalling.

**Comment by Cyberdroid1** [comment]
Since recent updates, I have not faced this issue for a while now. I will close this issue now. 
Thanks.
