### ISSUE TITLE
Outlike

### ISSUE THREAD

**Issue by aman89-code** [Jigsaw-Code/Intra#279]

**Comment by Ezi-lang** [comment]
👇

**Comment by cjhenck** [comment]
I'm afraid I don't know what you mean by "Outlike", so I'm closing this issue. Please feel free to reopen and add more details.

**Comment by Ezi-lang** [comment]
Какой code intra

ср, 2 сент. 2020 г., 17:58 Justin Henck <notifications@github.com>:
