### ISSUE TITLE
Outline

### ISSUE THREAD

**Issue by aman89-code** [Jigsaw-Code/Intra#280]

**Comment by cjhenck** [comment]
Are you suggesting that we add Outline functionality into Intra, or letting people know that Outline is an alternative?

**Comment by shatlyktma** [comment]
Barynyz bos  kodalry ugratman

пт, 13 нояб. 2020 г., 21:36 Justin Henck <notifications@github.com>:

**Comment by GudrunStoppelbart** [comment]
Do Outline and Intra play well together?

**Comment by cjhenck** [comment]
If you mean can you run both simultaneously, I'm afraid not. If you want to use an alternative DNS service with an Outline server you may consider trying a different Shadowsocks client.

**Comment by GudrunStoppelbart** [comment]
> If you mean can you run both simultaneously, I'm afraid not. If you want to use an alternative DNS service with an Outline server you may consider trying a different Shadowsocks client.

Thanks for the clarification. 
Is an integration of Intra into Outline planned or is that technically not possible?

**Comment by cjhenck** [comment]
@GudrunStoppelbart What's your use case? It would be possible, but Outline is already designed to encrypt everything between the phone and the Outline server.

**Comment by GudrunStoppelbart** [comment]
I am thinking about the Outline server using DNSCrypt/DNS-over-HTTPS with advertising, tracker and malware filtering.
