### ISSUE TITLE
Intra is not connect

### ISSUE THREAD

**Issue by GulAN821** [Jigsaw-Code/Intra#281]
Please help, intra is not connect...

**Comment by milanageydarova** [comment]
Емае не где нету блин 😂

**Comment by GulAN821** [comment]
> Емае не где нету блин 😂

Ага.

**Comment by ignoramous** [comment]
Check if you have any other VPN app setup as "Always-on VPN".

Settings -> Wifi and internet -> VPN 

And check if any other VPN app is "Always-on"

**Comment by milanageydarova** [comment]
> Проверьте, настроено ли какое-либо другое приложение VPN как «Постоянная VPN».
> 
> Настройки -> Wi-Fi и интернет -> VPN
> 
> И проверьте, работает ли какое-либо другое приложение VPN «Всегда включено»

А по человечески ?

**Comment by GulAN821** [comment]
> Check if you have any other VPN app setup as "Always-on VPN".
> 
> Settings -> Wifi and internet -> VPN
> 
> And check if any other VPN app is "Always-on"

Can not 😔 didn't work
