### ISSUE TITLE
ipv6 Support

### ISSUE THREAD

**Issue by shadowsaw** [Jigsaw-Code/Intra#286]
Intra completely disables ipv6 even if the dns servers have DOH capable ipv6 support and the device also has working ipv6 connectivity

**Comment by bemasc** [comment]
Yes, see #64 and #155.  Essentially, the problem is that the underlying LWIP library declares every socket successfully connected, even if IPv6 connectivity is not working, and this breaks the IPv6 detection logic in some apps.

**Comment by shadowsaw** [comment]
So the solution to this problem would be?

**Comment by bemasc** [comment]
The only solution I'm aware of would be to replace LWIP with a more flexible asynchronous TCP implementation, such as gVisor's tcpip package.  That would allow us to delay answering a SYN until after receiving a response from the server.

This would be a major change in Intra's architecture, so I don't expect it will happen any time soon.
