### ISSUE TITLE
Alyn intran taze kody https://DNS.hostux.net/dns-query

### ISSUE THREAD

**Issue by Resul99** [Jigsaw-Code/Intra#289]

**Comment by Ezi-lang** [comment]
Yone acanoga zasisena diyip dur

**Comment by perhat94** [comment]
basga kody yokmyka intranyn

**Comment by DU-MAX** [comment]
Intrany hic hilli acanoga
Basga kot yokmay


вт, 29 сент. 2020 г., 22:18 perhat94 <notifications@github.com>:

**Comment by marti-corolla** [comment]
https://DNS.adguard.com/dns-query şunda işlemese teliňde ýa da eliňde problema bar

**Comment by Elyas77** [comment]
Kim de islen server bar url yazin

**Comment by goshun2228** [comment]
Manada bar bolsa berayin
--
Отправлено из Mail.ru для Android среда, 21 октября 2020г., 22:10 +05:00 от Elyas77  notifications@github.com :

**Comment by cjhenck** [comment]
Please use #363
