### ISSUE TITLE
https://github.com/Jigsaw-Code/Intra.git     подключение beryar 

### ISSUE THREAD

**Issue by Serdarjan** [Jigsaw-Code/Intra#290]
https://github.com/Jigsaw-Code/Intra.git     подключение beryar

**Comment by Eziz07** [comment]
dos serverini goyayda

**Comment by Serdarjan** [comment]
> dos serverini goyayda

dns.hinet.net/dns-query

**Comment by mayajyk** [comment]
> dos serverini goyayda

Sende yokmy server

**Comment by mayajyk** [comment]
> https://github.com/Jigsaw-Code/Intra.git подключение beryar

Basga isleyan kod yokmyyyy?

**Comment by Eziz07** [comment]
> > https://github.com/Jigsaw-Code/Intra.git подключение beryar
> 
> Basga isleyan kod yokmyyyy?

https://DOH.WESTUS.PI-dns.com/dns-query   suny barlap gor hany

**Comment by ZeLiYT** [comment]
Basga **kod** yokmy???!

**Comment by mayajyk** [comment]
> > > https://github.com/Jigsaw-Code/Intra.git подключение beryar
> > 
> > 
> > Basga isleyan kod yokmyyyy?
> 
> https://DOH.WESTUS.PI-dns.com/dns-query suny barlap gor hany

İslanokda😣...

**Comment by marti-corolla** [comment]
Sagja bol Serdar şu wagta işleýär

**Comment by perhat94** [comment]
haysy kotda isleyarka

**Comment by mayajyk** [comment]
İşleyan kody bolup kod bermedigiň kody yapylsyn😑

**Comment by govhero** [comment]
kod

> > > > https://github.com/Jigsaw-Code/Intra.git подключение beryar
> > > 
> > > 
подключеие берйэ де не ютуб ачяр не де интаграм 😥😥😥

**Comment by Eziz07** [comment]
> İşleyan kody bolup kod bermedigiň kody yapylsyn😑

🤣🤣🤣 wah ol sende isleyan kod basga telefonda isleman bilyan eken

**Comment by Ezi-lang** [comment]
Basga yokmy bu islanok

пн, 12 окт. 2020 г., 20:20 perhat94 <notifications@github.com>:

**Comment by Resul99** [comment]
Salam doslar Intran taze kodyny tapsdym.Imo;nom///61212242

13 Eki 2020 Sal 18:08 tarihinde Ezi-lang <notifications@github.com> şunu
yazdı:

**Comment by toyl** [comment]
Kot uraday dos

чт, 1 окт. 2020 г., 20:03 Serdarjan <notifications@github.com>:

**Comment by shatlyktma** [comment]
> https://github.com/Jigsaw-Code/Intra.git подключение beryar

Servrr kod beryade

**Comment by shatlyktma** [comment]
Kod berayde

**Comment by cjhenck** [comment]
Please use #363
