### ISSUE TITLE
get new dns code

### ISSUE THREAD

**Issue by govhero** [Jigsaw-Code/Intra#292]
Where can I get a new working DNS code?

**Comment by Resul99** [comment]
blmoga dosy

13 Eki 2020 Sal 14:18 tarihinde govhero <notifications@github.com> şunu
yazdı:

**Comment by Gulruhbet** [comment]
Kod bilyanizmi

**Comment by guzel1968** [comment]
ёк
--
Отправлено из Mail.ru для Android среда, 21 октября 2020г., 18:09 +05:00 от Gulruhbet  notifications@github.com :

**Comment by guzel1968** [comment]
билсем хокман язарын
--
Отправлено из Mail.ru для Android среда, 21 октября 2020г., 18:09 +05:00 от Gulruhbet  notifications@github.com :
