### ISSUE TITLE
Şunda işlemese telefonyňy çalyş

### ISSUE THREAD

**Issue by marti-corolla** [Jigsaw-Code/Intra#293]
https://DNS.adguard.com/dns-query

**Comment by govhero** [comment]
👍👍👍

**Comment by govhero** [comment]
работает как швецарские часы

**Comment by BatyrAbdyyew** [comment]
Salam intrañ koduny ugradyp bilersiñizmi

20 окт. 2020 г. 9:37 пользователь "govhero" <notifications@github.com>
написал:
