### ISSUE TITLE
Lodd aydayyn hayyyyyyyyssssisleyan bolsun yone

### ISSUE THREAD

**Issue by Gulruhbet** [Jigsaw-Code/Intra#295]
Kod gerek aydayyn pazalusta

**Comment by Ezi-lang** [comment]
Barlap gor suny

вт, 20 окт. 2020 г., 20:53 Gulruhbet <notifications@github.com>:

**Comment by Marat77a7** [comment]
Gulruhbet     https://ibuki.cgnat.net/dns-query      bu kod mende islap dur. Barlap gor

**Comment by Marat77a7** [comment]
> Kod gerek aydayyn pazalusta

https://ibuki.cgnat.net/dns-query    barlap gor.

**Comment by guzel1968** [comment]
боля тапайын
--
Отправлено из Mail.ru для Android среда, 21 октября 2020г., 14:01 +05:00 от Marat77a7  notifications@github.com :

**Comment by Gulruhbet** [comment]
> Gulruhbet https://ibuki.cgnat.net/dns-query bu kod mende islap dur. Barlap gor

Islanoga

**Comment by Gulruhbet** [comment]
Islanok bla
