### ISSUE TITLE
Кому нужен код туркменистан от КЕНТ

### ISSUE THREAD

**Issue by azathan** [Jigsaw-Code/Intra#298]

**Comment by Julia-moon** [comment]
Кент это впн?

**Comment by guzel1968** [comment]
мне нужно
--
Отправлено из Mail.ru для Android среда, 21 октября 2020г., 13:59 +05:00 от Julia-moon  notifications@github.com :

**Comment by Julia-moon** [comment]
#гузель, у тя тоже интра не подключается?

**Comment by super-24** [comment]
https://dns.bentasker.co.uk/dns-query

**Comment by super-24** [comment]
Ishlese aydyn

**Comment by Bagul** [comment]
Привет всем супер 24 твой код не сработал(((

**Comment by Bagul** [comment]
Не работает (((

**Comment by Elyas77** [comment]
Kim de bar islen url

**Comment by super-24** [comment]
https://doh.westus.pi-dns.com/dns-query
Muny gorun

**Comment by govhero** [comment]
бесполезно нлвый код искатт даже если найдёшь всеравно долго не сможешь сидет максимум через час по любому закрывают

**Comment by ArsLan80** [comment]
> https://doh.westus.pi-dns.com/dns-query
> Muny gorun

Işlanok

**Comment by Julia-moon** [comment]
Надоедает  , у меня уже ничего не работает😟

**Comment by GulAN821** [comment]
https://doh-2.Seby.io/dns-query 
Попробуйте этот

**Comment by Bagul** [comment]
Не сработал (((

чт, 22 окт. 2020 г., 20:36 GulAN821 <notifications@github.com>:

**Comment by Julia-moon** [comment]
Не получилось )

**Comment by God-lightning-coder** [comment]
Привет всем ребята кто знает код для интра впн

**Comment by cjhenck** [comment]
Please use #363

**Comment by Shanur05** [comment]
Isleyan server men bilyan

**Comment by Shanur05** [comment]
У меня есть работаюший сервер

**Comment by Shanur05** [comment]
https://github.com/users/Shanur05/projects/1#card-70979653

**Comment by Maksatgm** [comment]
Salam ishleyan server bamy pubg acyamy

**Comment by govhero** [comment]
pubg oynamok inst açýa

пн, 17 янв. 2022 г., 4:20 Maksatgm ***@***.***>:

**Comment by Zarinadurdyyeva** [comment]
Selam kod yok mu?

**Comment by amanbay716** [comment]
Kod näme

**Comment by Sohbet2005** [comment]
Intra server barmyka?

**Comment by Kuwwataga** [comment]
Salawmaleýkim duzup bilyanler bar bolsa isleyan server oklayyn

**Comment by Zarinadurdyyeva** [comment]
Mana ugradayin hayis

сб, 25 марта 2023, 22:30 Kuwwataga ***@***.***>:

**Comment by selimlai** [comment]
Domain bolsa ozumizem duzyas vpn yone domain yok ishleyanlerem yapylyp dur.

**Comment by Kuwwataga** [comment]
Düşündim tazelik bolsa habsr edaýin haýyş sizden

пн, 17 июл. 2023 г., 13:31 selimlai ***@***.***>:

**Comment by batyrhemrakulyev** [comment]
Привет мне нужен код интра впн

**Comment by Caryeva110899** [comment]
Привет мне нужна код интро впн

**Comment by guvanchhydyrow** [comment]
Kimde npv tunnel configuration bar bolsa berayin
