### ISSUE TITLE
Я работаю над кодом придеться вам ждать сутки

### ISSUE THREAD

**Issue by azathan** [Jigsaw-Code/Intra#302]
Данный сервер будет работать примерно 10ть дней

**Comment by marhabo393** [comment]
Berekella!! Şu tayyk yazyañmy kody ???

**Comment by marhabo393** [comment]
> Данный сервер будет работать примерно 10ть дней

Berekella!! Şu tayyk yazyañmy kody ???

**Comment by dima0092** [comment]
Где напишешь ?

**Comment by gulruh780** [comment]
манада берин хайыш 😔😔

**Comment by gulruh780** [comment]
алооо

**Comment by Bagul** [comment]
Молодец сюда напиши, ждём!

**Comment by Bagul** [comment]
Эляс 77 не работает (((, хотя у меня новый телефон редми 9а и там все обновила все платформы и т.д и т.п

**Comment by Julia-moon** [comment]
🙏🙏🙏🙏🙏

**Comment by ArsLan80** [comment]
Intranyn kody gerek

**Comment by Bagul** [comment]
Ну как нашли кол интры? И подскажите пожалуйста как открыть Инстаграм?

**Comment by Gulruhbet** [comment]
Kod berayyyin
