### ISSUE TITLE
Над данным кодом ещё идет обработка https://trashbox.ru/files30/1084489/net

### ISSUE THREAD

**Issue by azathan** [Jigsaw-Code/Intra#303]
От КЕНТ

**Comment by Bagul** [comment]
Хорошо главное не забыть написать код спс)))

**Comment by Elyas77** [comment]
Islyan kod gerek https://doh-2.seby.io/dns-query buu islenok

**Comment by enegulrahmanova** [comment]
пожалуйста по быстрее мне срочно нужен новый код

**Comment by Ezi-lang** [comment]
Gayrat edin isleyan kod berayin

чт, 22 окт. 2020 г., 22:09 enegulrahmanova <notifications@github.com>:

**Comment by sehmus1042** [comment]
https://trashbox.ru/files30/1084489/net
почему не работайет этот код

**Comment by ArsLan80** [comment]
Hany kod tayyn bolmadymy

**Comment by OrazMuradov** [comment]
Manada bersenizlan kody cyksa

**Comment by sehmus1042** [comment]
sol kod kabir telde isleya yone menda islanok


пт, 23 окт. 2020 г., 9:08 AM Oraz <notifications@github.com>:

**Comment by OrazMuradov** [comment]
Mendede islanokda sho, yada obrabotkasy gutaryanca garashmalymy?

**Comment by sehmus1042** [comment]
owa  garash bolmasada Z-VPN isleya

пт, 23 окт. 2020 г., 9:12 AM Oraz <notifications@github.com>:

**Comment by OrazMuradov** [comment]
z vpn dp yazdym velin uc dort sany cykdyda haysysy bulan

пт, 23 окт. 2020, 9:13 sehmus1042 <notifications@github.com>:

**Comment by mayajyk** [comment]
Kod berayinda islanoga bul

**Comment by OrazMuradov** [comment]
ay sho koda bizede gerek

пт, 23 окт. 2020, 15:12 mayajyk <notifications@github.com>:

**Comment by mayajyk** [comment]
Mmm🙄

23 Eki 2020 Cum 15:13 tarihinde Oraz <notifications@github.com> şunu yazdı:

**Comment by Bagul** [comment]
Менде модели уррра!


пт, 23 окт. 2020 г., 15:49 mayajyk <notifications@github.com>:

**Comment by mayajyk** [comment]
Bersene bizede

23 Eki 2020 Cum 16:56 tarihinde Bagul <notifications@github.com> şunu yazdı:

**Comment by Elyas77** [comment]
Taze tapdinzmi kod

**Comment by sehmus1042** [comment]
вс, 25 окт. 2020 г., 1:24 PM Elyas77 <notifications@github.com>:

**Comment by cjhenck** [comment]
Please use #363
