### ISSUE TITLE
server intra

### ISSUE THREAD

**Issue by shatlyktma** [Jigsaw-Code/Intra#306]

**Comment by shatlyktma** [comment]
https://trashbox.ru/files30/1084489/net

**Comment by sehmus1042** [comment]
islanok su arada islegen yaly edya son islemeya gosya ayirya basga bolan zat yok yutuby acanok

**Comment by sehmus1042** [comment]
https://cla.developers.google.com/ isleya yone yutuby acanok

**Comment by shatlyktma** [comment]
Acyani yokmi sende

сб, 24 окт. 2020 г., 20:27 sehmus1042 <notifications@github.com>:

**Comment by sehmus1042** [comment]
https://trashbox.ru/files30/1084489/net intrany isletya yutuba girenok

сб, 24 окт. 2020 г., 8:32 PM shatlyktma <notifications@github.com>:

**Comment by Ezi-lang** [comment]
Name vpn bilyan

сб, 24 окт. 2020 г., 20:33 sehmus1042 <notifications@github.com>:

**Comment by shatlyktma** [comment]
Bolia sawol tazelik bolsa ugrat menem ulgamda men

сб, 24 окт. 2020 г., 20:33 sehmus1042 <notifications@github.com>:

**Comment by sehmus1042** [comment]
yok acanok

сб, 24 окт. 2020 г., 8:41 PM shatlyktma <notifications@github.com>:
