### ISSUE TITLE
Berayin taze kody ba bolsa kimde bolsa

### ISSUE THREAD

**Issue by OrazMuradov** [Jigsaw-Code/Intra#307]
Nazini cekdirday bu intrada belli bir kodunda duranok

**Comment by OrazMuradov** [comment]
https://m.arkansso.com/dns-query shuny barlap gorun ishleya diydiler menkida ishlanok

**Comment by ay9889** [comment]
https://hub.docker.com/u/ich777

**Comment by mahym575** [comment]
başga ýokmy bilýäniňiz???

**Comment by sazak81** [comment]
https://m.arkansso.com/dns-query - бул гошанок, https://hub.docker.com/u/ich777 - бу гошья ёне ютуб ачанок

**Comment by Elyas77** [comment]
Taze kody manda gerek kimde bar bolsa

**Comment by Elyas77** [comment]
https://162.159.132.53/dns-query ishleya
30 Окт 2020 г. 12:49 PM пользователь "Oraz" <notifications@github.com>
написал:

**Comment by cjhenck** [comment]
Please use #363

**Comment by shatlyktma** [comment]
Kod ugradyn bratiska

пт, 13 нояб. 2020 г., 23:19 Justin Henck <notifications@github.com>:
