### ISSUE TITLE
https://doh-2.Seby.io/dns-query

### ISSUE THREAD

**Issue by shatlyktm** [Jigsaw-Code/Intra#308]

**Comment by Gulruhbet** [comment]
IslAnoookk

**Comment by shatlyktm** [comment]
https://hk-dns.233py.com/dns-query
Ine sul islap dur

пн, 26 окт. 2020 г., 15:44 Gulruhbet <notifications@github.com>:

**Comment by Julia-moon** [comment]
shatlyktm) инни ишланок йене

**Comment by jedisct1** [comment]
https://dnscrypt.info/public-servers

**Comment by meloni397** [comment]
jedisct1 ishlanok bulam 😫😖 hic yokmyka ishleyani. Eger tapsanyz goyayn .

**Comment by Abdyreshit** [comment]
https://hub.docker.com/u/ich777 шул коп адамда ишлея

**Comment by meloni397** [comment]
Abdyreshit sag bol kop kop🤗🤗🤗

**Comment by meloni397** [comment]
Ay bulam zashita beryada yutuby ishledenok eken

**Comment by Elyas77** [comment]
YouTube acman duu
27 Окт 2020 г.
>
> https://hub.docker.com/u/ich777 шул коп адамда ишлея

**Comment by cjhenck** [comment]
Please use #363

**Comment by shatlyktma** [comment]
Grupba yokmi

пт, 13 нояб. 2020 г., 23:19 Justin Henck <notifications@github.com>:

**Comment by shatlyktma** [comment]
Kod ugratda

сб, 14 нояб. 2020 г., 19:41 Shatlyk Babaniyazov <shatlyktma@gmail.com>:

**Comment by shatlyktma** [comment]
https://kracon.anycast.censurfridns.dk/dns-query

сб, 14 нояб. 2020 г., 19:44 Shatlyk Babaniyazov <shatlyktma@gmail.com>:

**Comment by shatlyktma** [comment]
Intran kody

Https://kracon.anycast.censurfridns.DK/dns-query

сб, 14 нояб. 2020 г., 23:26 Shatlyk Babaniyazov <shatlyktma@gmail.com>:
