### ISSUE TITLE
https://IBKSTURM.SYNOLOGY.ME/dns-query

### ISSUE THREAD

**Issue by shatlyktm** [Jigsaw-Code/Intra#309]

**Comment by mayajyk** [comment]
Yutuba girenok😣

**Comment by Gulruhbet** [comment]
Https://fastbravedns.com/hussain1 barlap gorun men ozum duzdim

**Comment by mayajyk** [comment]
İşlanoga guşşam

26 Eki 2020 Pzt 09:35 tarihinde Gulruhbet <notifications@github.com> şunu
yazdı:

**Comment by Gulruhbet** [comment]
On 1hepde isledi indi yapyldy

**Comment by mayajyk** [comment]
Düzsene onda yene)

26 Eki 2020 Pzt 09:43 tarihinde Gulruhbet <notifications@github.com> şunu
yazdı:

**Comment by Gulruhbet** [comment]
Kyn a ozum 13 yasymda

**Comment by sazak81** [comment]
https://IBKSTURM.SYNOLOGY.ME/dns-query Интра гошья ёне ютуб ачанок

**Comment by Ezi-lang** [comment]
https://233PY.com/dns-query me alyn doslar

пн, 26 окт. 2020 г., 20:00 sazak81 <notifications@github.com>:

**Comment by sazak81** [comment]
https://233PY.com/dns-query интра вапше гошуланок мунда

**Comment by oraz1992** [comment]
https://hub.docker.com/u/ich777

**Comment by Elyas77** [comment]
Hokman
28 Окт 2020 г. 8:57 пользователь "oraz1992" <notifications@github.com>
написал:

**Comment by cjhenck** [comment]
Please use #363

**Comment by ibksturm** [comment]
> Интра гошья ёне ютуб ачанок

whats the problem? i updatet some hardware and software the last 2 years
