### ISSUE TITLE
Jemal Rejepowa

### ISSUE THREAD

**Issue by JemalRejepowa** [Jigsaw-Code/Intra#311]
Kımde kod ba bolsa berayın

**Comment by oraz1992** [comment]
https://hk-dns.233py.com/dns-query

**Comment by oraz1992** [comment]
https://hub.docker.com/u/ich777

**Comment by mahym575** [comment]
https://DOH.WESTUS.PI-dns.com/dns-query

**Comment by cjhenck** [comment]
Please use #363
