### ISSUE TITLE
https://233PY.com/dns-query

### ISSUE THREAD

**Issue by oraz1992** [Jigsaw-Code/Intra#312]

**Comment by oraz1992** [comment]
https://233PY.com/dns-query

**Comment by dulik92** [comment]
Не подключается. Скиньте пожалуйста работающий.

**Comment by oraz1992** [comment]
Turkmenistanda isleya su dogry gocur
https://hk-dns.233py.com/dns-query

**Comment by oraz1992** [comment]
https://hub.docker.com/u/ich777

**Comment by cjhenck** [comment]
Please use #363
