### ISSUE TITLE
На удачу

### ISSUE THREAD

**Issue by Nebesnuu** [Jigsaw-Code/Intra#313]
https://ourserver.org/somesecret/vpn/on
Просто вставляете делаете принять и пользуетесь...без днс

**Comment by govhero** [comment]
ага, и что это? 😕😕😕

**Comment by oraz02a** [comment]
Intraň kodyny beräýin

**Comment by OrazMuradov** [comment]
> https://ourserver.org/somesecret/vpn/on
> Просто вставляете делаете принять и пользуетесь...без днс

Ishlanoga

**Comment by oraz1992** [comment]
https://hk-dns.233py.com/dns-query
Turkmenisdanda isleya intra kod sul

**Comment by oraz02a** [comment]
Mende ikisem işänok

**Comment by toylykaka** [comment]
men näme edeyin
--
Отправлено из myMail для Android среда, 28 октября 2020г., 08:34 +05:00 от oraz02a  notifications@github.com :

**Comment by oraz1992** [comment]
https://hub.docker.com/u/ich777

**Comment by OrazMuradov** [comment]
yutuby acanoga dos

ср, 28 окт. 2020, 8:56 oraz1992 <notifications@github.com>:

**Comment by oraz02a** [comment]
https://hub.docker.com/u/ich777
Isleya yone you tube acanok

**Comment by Elyas77** [comment]
Шейдип дуу
28 Окт 2020 г. 9:12 AM пользователь "oraz02a" <notifications@github.com>
написал:

**Comment by OrazMuradov** [comment]
utub acyany tapylmazmyka dos

ср, 28 окт. 2020, 9:14 Elyas77 <notifications@github.com>:

**Comment by Elyas77** [comment]
Херхли ларин гордум ишлнок биламок на учин
28 Окт 2020 г. 9:16 пользователь "Oraz" <notifications@github.com> написал:

**Comment by OrazMuradov** [comment]
Yutub acyany tapylsa yazayynda kyn gorman

**Comment by cjhenck** [comment]
Please use #363
