### ISSUE TITLE
Işleýa şul!

### ISSUE THREAD

**Issue by Farruh1591** [Jigsaw-Code/Intra#317]

**Comment by Elyas77** [comment]
Sagbol isledy
29 Окт 2020 г. 8:55 PM пользователь "Farruh1591" <notifications@github.com>
написал:

**Comment by OrazMuradov** [comment]
Haysy kod ishleya

**Comment by meloni397** [comment]
Indi ishlanok bulam, жаль.

**Comment by JemalRejepowa** [comment]
Inı oda ışlanok basga kod bamy
