### ISSUE TITLE
Kod berayin

### ISSUE THREAD

**Issue by Gulruhbet** [Jigsaw-Code/Intra#319]

**Comment by ArsLan80** [comment]
https://118.31.13.131/dns-query

**Comment by Elyas77** [comment]
👍

сб, 31 Окт 2020, 19:00 Lion_black <notifications@github.com>:

**Comment by Elyas77** [comment]
Sagbol isledy

сб, 31 Окт 2020, 19:00 Lion_black <notifications@github.com>:

**Comment by cjhenck** [comment]
Please use #363
