### ISSUE TITLE
Мой код

### ISSUE THREAD

**Issue by Nebesnuu** [Jigsaw-Code/Intra#321]
Хорошим людям
https://t.me/joinchat/AAAAAE8MWtKYBW9zYIeuMQ

**Comment by GulAN821** [comment]
> Хорошим людям
> https://t.me/joinchat/AAAAAE8MWtKYBW9zYIeuMQ

Спасибо, но не работает

**Comment by fortuna** [comment]
The link doesn't work:
![image](https://user-images.githubusercontent.com/113565/99113759-c6d7a500-25bd-11eb-9c4f-08ebf3b15323.png)
