### ISSUE TITLE
Intra kod beriň haýiş 👍

### ISSUE THREAD

**Issue by atabek1990** [Jigsaw-Code/Intra#322]

**Comment by Wepa1982** [comment]
https://DOH.WESTUS.PI-dns.com/dns-query

**Comment by dulik92** [comment]
Не подключается https://DOH.WESTUS.PI-dns.com/dns-query

**Comment by sazak81** [comment]
https://DOH.WESTUS.PI-dns.com/dns-query. Ишланок бул

**Comment by Tom-web777** [comment]
Islap duran kody paylasyp gote urdyn, indi ishlanok

**Comment by Julia-moon** [comment]
Don't working
