### ISSUE TITLE
> https://162.159.36.1/dns-query şu kod ýaman gowy açýa kime gerek bolsa alyň

### ISSUE THREAD

**Issue by enegulrahmanova** [Jigsaw-Code/Intra#325]
> https://162.159.36.1/dns-query в данный момент работает

şuny kim ýazan bolsada köp köp sagbol betinden açýar

_Originally posted by @enegulrahmanova in https://github.com/Jigsaw-Code/Intra/issues/324#issuecomment-722232521_

**Comment by amara54** [comment]
Sagbol😊

**Comment by faruh890** [comment]
Ishlenok

**Comment by marti-corolla** [comment]
👍👍👍👍👍👍👍👍👍👍

**Comment by Elyas77** [comment]
Pecat acip duu 👍👍👍👍👍

чт, 5 Ноя 2020, 21:19 marti-corolla <notifications@github.com>:

**Comment by Gulruhbet** [comment]
Anada

**Comment by shatlyktma** [comment]
Cmo bollet

пт, 13 нояб. 2020 г., 21:34 Justin Henck <notifications@github.com>:
