### ISSUE TITLE
Intra kod

### ISSUE THREAD

**Issue by Gulruhbet** [Jigsaw-Code/Intra#327]
https://dns.wcc.best/dns-queryhttps://162.159.36.1/dns-queryhttps://139.224.112.177/dns-queryhttps://162.159.36.1/dns-queryhttps://dns-nyc.aaflalo.me/dns-queryhttps://youtu.be/bcg_27AbUEYhttps://dns.alidns.com/dns-queryhttps://dns1.quickline.ch/dns-queryhttps://IBKSTURM.SYNOLOGY.ME/dns-queryhttps://59.110.53.209/dns-queryhttps://arashi.doh.pp.ua/dns-queryhttps://139.224.112.177/dns-query

**Comment by mahym575** [comment]
ishleyan kodyny yazayyn, please

**Comment by Gulruhbet** [comment]
Sular isleyada

**Comment by Didar357** [comment]
Dossym haysy kot isleya

**Comment by Gulruhbet** [comment]
> Dossym haysy kot isleya

Hemmesinem barlap goray

**Comment by atabek1990** [comment]
https://arashi.doh.pp.ua/dns-query

**Comment by cjhenck** [comment]
Please use #363
