### ISSUE TITLE
Intranyn serveri gerek (kody)

### ISSUE THREAD

**Issue by ALLANUR-Code** [Jigsaw-Code/Intra#331]
Kimde intarnyn serveri bar bolsa ugradan

**Comment by arslsn** [comment]
Ugrat

**Comment by ALLANUR-Code** [comment]
Mana gerek
________________________________

**Comment by Gulruhbet** [comment]
https://162.159.36.1/dns-queryhttps://dns2.quickline.ch/dns-queryhttps://doh.centraleu.pi-dns.com/dns-query Intra✅https://bugs.chromium.org/p/chromium/issues/detail?id=799753 Intra✅https://resolver-eu.lelux.fi/dns-queryhttps://eu1.dns.lavate.ch/dns-queryhttps://dns-family.adguard.com/dns-queryhttps://dns.east.comss.one/dns-queryhttps://doh.eastas.pi-dns.com/dns-queryhttps://doh.eastas.pi-dns.com/dns-query

**Comment by ALLANUR-Code** [comment]
Islanok yone sul isleyar https://us1.dns.lavate.ch/dns-query
________________________________

**Comment by Elyas77** [comment]
https://dns2.quickline.ch/dns-query

вс, 8 Ноя 2020, 22:42 ALLANUR-Code <notifications@github.com>:

**Comment by cjhenck** [comment]
Please use #363
