### ISSUE TITLE
GULRUHBET

### ISSUE THREAD

**Issue by shatlyktm** [Jigsaw-Code/Intra#333]
GULRUH BET ZAMIKANIYA BERYAMI TELFONYN YAPYLMAYAM SERVER BEREYIN 

https://DNS2.quickline.ch/dns-query

**Comment by wepailyas** [comment]
Шатлыктм şonyña işlanok

**Comment by wepailyas** [comment]
https://us1.dns.lavate.ch/dns-query 
Şujagazam barlap goriñ

**Comment by cjhenck** [comment]
Please use #363
