### ISSUE TITLE
Intra kod 9.11.2020 20:49 Gulruhbet

### ISSUE THREAD

**Issue by Gulruhbet** [Jigsaw-Code/Intra#334]
Kad berayin hayyys

**Comment by crew4651** [comment]
Ким де ба код

**Comment by kulhanow** [comment]
Kod berayin ishleyan gyn gorman

**Comment by amara54** [comment]
https://m.winline.ru/dns-query sul kody gor

**Comment by mahym575** [comment]
beräýiň kodyny kim işledýän bolsa gaty gyssagly gerek pleaseee

**Comment by cjhenck** [comment]
Please use #363
