### ISSUE TITLE
Intra kody

### ISSUE THREAD

**Issue by oraz02a** [Jigsaw-Code/Intra#338]
Intran kodyny beräýin pls

**Comment by oraz02a** [comment]
https://bravedns.com/configure

**Comment by mayajyk** [comment]
Oraz İslanoga buuu

**Comment by oraz02a** [comment]
https://arashi.doh.pp.ua/dns-query

**Comment by oraz02a** [comment]
Sxu işleýa

**Comment by Kemal-del** [comment]
Спасиба Ораз

**Comment by JemalRejepowa** [comment]
Işlanoga Oraz

**Comment by JemalRejepowa** [comment]
Şol kod you tube açyamı sızlerde

**Comment by oraz02a** [comment]
https://us1.dns.lavate.ch/dns-query

**Comment by oraz02a** [comment]
Sxu kodam barlap gor hany

**Comment by ALLANUR-Code** [comment]
islanok

**Comment by oraz02a** [comment]
https://us1.dns.lavate.ch/dns-query sxu koda garaşmaly kopirak ozi islap baslaya

**Comment by ALLANUR-Code** [comment]
hm bolya

**Comment by Kemal-del** [comment]
Mende yene işlanok

**Comment by oraz02a** [comment]
Dos imo gelay 65309285

**Comment by JemalRejepowa** [comment]
Kod bılenızokmy

**Comment by cjhenck** [comment]
Please use #363
