### ISSUE TITLE
10.11.20 INTRA KOD GEREKDI SROCNA

### ISSUE THREAD

**Issue by Nurgozel005** [Jigsaw-Code/Intra#341]
Alla omrunizi uzak etsin Intra kod berayiin

**Comment by mahym575** [comment]
coolv.p.n ulanyp goraymesen bu wagt yoga hic yerde bolsa yazayyn

**Comment by Nurgozel005** [comment]
wiyy men android versiyam goterenoga cool vpny.sps aydanyn ucin
