### ISSUE TITLE
Intra kody

### ISSUE THREAD

**Issue by Nurgozel005** [Jigsaw-Code/Intra#342]
https://mendeyok.dns.com/dns-query
https://sizdebarmy.intrakod.com/dns-query
https://bolsaberayin.dns.ch/dns-query

**Comment by Nurgozel005** [comment]
https://dns2.quickline.ch/dns-query islap dur

**Comment by mahym575** [comment]
ishlemedi(((

**Comment by Nurgozel005** [comment]
onna bilemok manada gerek bar bolsa

**Comment by atabek1990** [comment]
https://bolsaberayin.dns.ch/dns-query
Şu kod ishledi 😄😂🤣🤣🤣

**Comment by mahym575** [comment]
> https://bolsaberayin.dns.ch/dns-query
> Şu kod ishledi 😄😂🤣🤣🤣

O kod işleýä (her kim tapanjasyny goýýa) ýöne işleýäni ýok

**Comment by atabek1990** [comment]
> > https://bolsaberayin.dns.ch/dns-query 
> > Şu kod ishledi😄😂🤣🤣🤣
> 
> O kod işleýä (ее kim tapanjasyny goýýa) ýöne işleýäni 
@Musa https://cubedns.com/dns-query  mahim575 al şu işlapdur garantiýa👍😉😉🇹🇲

**Comment by cjhenck** [comment]
Please use #363

**Comment by jemalhemrayew** [comment]
İntra kod barmy hayys berayin

**Comment by Sohbet2005** [comment]
Kimde bar intra kody berayin.

**Comment by Gurbanberdi** [comment]
Alo

**Comment by Ne0xor16** [comment]
Че там кодов нет?

**Comment by Ne0xor16** [comment]
> https://dns.skrzypiec.pl/dns-query My private server. Blocks ads, trackers and phishing sites.

This don't work telecom!
