### ISSUE TITLE
Kimde intraň kody ba bolsa haýyş beräýiň!!!

### ISSUE THREAD

**Issue by enegulrahmanova** [Jigsaw-Code/Intra#343]
kim täze kod tapsa kyn görmän şu taýyk ýazaýyň

**Comment by Ayna147** [comment]
Ok

**Comment by Ayna147** [comment]
Https://Dns.bentasker.co.Uk/dns-query barlap gorun isleya su

**Comment by toyl** [comment]
Mende

вт, 10 нояб. 2020 г., 22:32 Ayna147 <notifications@github.com>:

**Comment by enegulrahmanova** [comment]
Https://Dns.bentasker.co.Uk/dns-query barlap gorun isleya su
Ayna147 spasibo köp köp işleýä

**Comment by cjhenck** [comment]
Please use #363
