### ISSUE TITLE
Https://Dns.bentasker.co Uk intran taze kody

### ISSUE THREAD

**Issue by Ayna147** [Jigsaw-Code/Intra#344]

**Comment by mahym575** [comment]
shu yerik yazayyn kodyny achylanok

**Comment by JemalRejepowa** [comment]
İşlanoga

**Comment by JemalRejepowa** [comment]
Https://Dns.bentasker.co.UK/dns-query

**Comment by toyl** [comment]
https://dns.alidns.com/dns-query

вт, 10 нояб. 2020 г., 23:50 JemalRejepowa <notifications@github.com>:

**Comment by Ayna147** [comment]
Isleya barlan yenede mende acyp dur

**Comment by cjhenck** [comment]
Please use #363
