### ISSUE TITLE
Alyn onda yene tz kod

### ISSUE THREAD

**Issue by Ayna147** [Jigsaw-Code/Intra#345]

**Comment by Ayna147** [comment]
Https://DOH.FFMUC.NET/dns-query
Https://dns.bentasker.co.Uk/dns-query
Ikisem islapdur

**Comment by guych117** [comment]
Ikisem ishlanok

**Comment by Ayna147** [comment]
Garasyp arasynda durup isleya

**Comment by dulik92** [comment]
https://DOH.FFMUC.NET/dns-query в данный момент работает

**Comment by Ayna147** [comment]
Menda ikisem isleya blkm sizde nm uc islemeyanini🤔

**Comment by JemalRejepowa** [comment]
Olaram ışlanok başga kod yokmy

**Comment by cjhenck** [comment]
Please use #363
