### ISSUE TITLE
Intran tz kody

### ISSUE THREAD

**Issue by Ayna147** [Jigsaw-Code/Intra#347]
Https://kracon.anycast.censurfridns.dk/dns-query barlak gorun menda isleya

**Comment by mayajyk** [comment]
Ayna saol isledi

**Comment by mayajyk** [comment]
Ayna su vagt yapyldy basga kod yokmuuu

**Comment by Nurgozel005** [comment]
Yapyldy bu kod tazesi yokmy?

**Comment by mayajyk** [comment]
Bolsa bizede ber

12 Kas 2020 Per 19:00 tarihinde Nurgozel Ovezova <notifications@github.com>
şunu yazdı:

**Comment by cjhenck** [comment]
Please use #363
