### ISSUE TITLE
INTRA KOD TÄZELENIPDIR.BERÄÝINDÄ HAÝYŞ

### ISSUE THREAD

**Issue by Nurgozel005** [Jigsaw-Code/Intra#348]

**Comment by mira1010** [comment]
Kmde ba intra kod

**Comment by mayajyk** [comment]
Psiphonam isleya

**Comment by Ezi-lang** [comment]
чт, 12 нояб. 2020 г., 19:14 Mirat <notifications@github.com>:

**Comment by Ezi-lang** [comment]
чт, 12 нояб. 2020 г., 19:16 mayajyk <notifications@github.com>:
