### ISSUE TITLE
Täze kod ba bolso berayń

### ISSUE THREAD

**Issue by mira1010** [Jigsaw-Code/Intra#349]
Taze kod berayin

**Comment by Ezi-lang** [comment]
чт, 12 нояб. 2020 г., 19:17 Mirat <notifications@github.com>:

**Comment by Ezi-lang** [comment]
https://lodab.klabnet.//dns-query

чт, 12 нояб. 2020 г., 19:24 Eziz Şämiýew <ezizsamiew9611@gmail.com>:

**Comment by mira1010** [comment]
Işlemeýä

**Comment by n674** [comment]
Kod beriň

**Comment by Nurgozel005** [comment]
INTRA KOD

**Comment by n674** [comment]
https://185.38.62.183/dns-query

**Comment by Gulruhbet** [comment]
Satlyk kod bar 3 manat 61038055

**Comment by cjhenck** [comment]
Please use #363
