### ISSUE TITLE
INTRA KOD https://cubedns.com/dnsquery

### ISSUE THREAD

**Issue by Gulruhbet** [Jigsaw-Code/Intra#350]
Indi.mugt

**Comment by arslsn** [comment]
Karzina berayde😅😅😅

**Comment by Gulruhbet** [comment]
> puly okla kody al shshshshs

**Comment by mahym575** [comment]
biznes etjek yeriniza tapdynyz

**Comment by mayajyk** [comment]
Paşolsanai iki sagatdan yapljak kodna pul berernmai gotine sok sony

**Comment by crew4651** [comment]
https://kracon.anycast.censurfridns.dk/dns-query

**Comment by Gulruhbet** [comment]
> Paşolsanai iki sagatdan yapljak kodna pul berernmai gotine sok sony

Sen eday

**Comment by mayajyk** [comment]
Https://Dns.bentasker.co.UK/dns-query

**Comment by arslsn** [comment]
Işlanok

**Comment by Gulruhbet** [comment]
> Işlanok

Işleya bok iyme

**Comment by cjhenck** [comment]
Please use #363
