### ISSUE TITLE
https://kracon.anycast.censurfridns.dk/dns-query

### ISSUE THREAD

**Issue by crew4651** [Jigsaw-Code/Intra#351]
Новый код https://kracon.anycast.censurfridns.dk/dns-query

**Comment by begaly86** [comment]
Spasibo

**Comment by begaly86** [comment]
Islenok

**Comment by cjhenck** [comment]
Please use #363

**Comment by shatlyktma** [comment]
Gulruh bet barmi janm
--
Отправлено из Mail.ru для Android пятница, 13 ноября 2020г., 23:15 +05:00 от Justin Henck  notifications@github.com :
