### ISSUE TITLE
Taze kod al kime gerek bolsa

### ISSUE THREAD

**Issue by arslsn** [Jigsaw-Code/Intra#354]
https://kracon.anycast.censurfridns.dk/dns-query

**Comment by mahym575** [comment]
😭😭😭😭

**Comment by shatlyktma** [comment]
https://tr.pinterest.com/dns-query

пт, 13 нояб. 2020 г., 14:39 mahym575 <notifications@github.com>:

**Comment by mahym575** [comment]
thanks❤️❤️❤️❤️

**Comment by JemalRejepowa** [comment]
Shatlyktma ol kod you tube açanok

**Comment by JemalRejepowa** [comment]
Başga yokmy

**Comment by JemalRejepowa** [comment]
You tube açyan

**Comment by shatlyktma** [comment]
https://tigobusiness.com.ni/doh

пт, 13 нояб. 2020 г., 18:56 JemalRejepowa <notifications@github.com>:

**Comment by cjhenck** [comment]
Please use #363

**Comment by Ismayyl** [comment]
İntran kody gerek kimde bar
