### ISSUE TITLE
Intran taze kody gerek

### ISSUE THREAD

**Issue by mira1010** [Jigsaw-Code/Intra#355]
Intran taze kody gerek pž

**Comment by ereshow** [comment]
Bolsa bizede gerek😮😮

**Comment by shatlyktma** [comment]
https://tr.pinterest.com/dns-query

пт, 13 нояб. 2020 г., 15:13 Mirat <notifications@github.com>:

**Comment by shatlyktma** [comment]
https://tr.pinterest.com/dns-query

пт, 13 нояб. 2020 г., 15:37 ereshow <notifications@github.com>:

**Comment by mira1010** [comment]
https://cubedns.com/dns-query

**Comment by cjhenck** [comment]
Please use #363

**Comment by behruz93** [comment]
254f54gh7745gfs35hjk8j5mn

**Comment by mammedowkemal61-beep** [comment]
Intra
