### ISSUE TITLE
Intra code by Gulruhbet

### ISSUE THREAD

**Issue by Gulruhbet** [Jigsaw-Code/Intra#357]
https://deic-ore.anycast.censurfridns.dk/

**Comment by JemalRejepowa** [comment]
Sps Gulruhbet

**Comment by maks006** [comment]
Saol

**Comment by shatlyktma** [comment]
https://deic-ore.anycast.censurfridns.dk/

пт, 13 нояб. 2020 г., 18:54 Gulruhbet <notifications@github.com>:

**Comment by shatlyktma** [comment]
Aklym basga server yokmi men isde oturn  wi fi yok

пт, 13 нояб. 2020 г., 19:46 Shatlyk Babaniyazov <shatlyktma@gmail.com>:

**Comment by JemalRejepowa** [comment]
Bu öçdu başga yokmy

**Comment by cjhenck** [comment]
Please use #363
