### ISSUE TITLE
SLAMA

### ISSUE THREAD

**Issue by Gulruhbet** [Jigsaw-Code/Intra#358]
slam

**Comment by mayajyk** [comment]
Gözňi pul bürapdir

**Comment by shatlyktma** [comment]
Gerek bolsa ozine aydayyn code serahs

пт, 13 нояб. 2020 г., 20:54 Gulruhbet <notifications@github.com>:

**Comment by mayajyk** [comment]
Aydayaaa satlyktma

**Comment by Gulruhbet** [comment]
> Gözňi pul bürapdir

Ondadama isleyan kodlaru beryan sen ulanokmy solary ha gaydyp kpd goymayan

**Comment by shatlyktma** [comment]
Men kod paylap ankam asdy basym aylanya indi

пт, 13 нояб. 2020 г., 21:02 mayajyk <notifications@github.com>:

**Comment by shatlyktma** [comment]
Vista vpn acyp beryan indi adamlara

пт, 13 нояб. 2020 г., 21:06 Shatlyk Babaniyazov <s.babaniyazow@yandex.com>:

**Comment by mayajyk** [comment]
> > Gözňi pul bürapdir
> 
> Ondadama isleyan kodlaru beryan sen ulanokmy solary ha gaydyp kpd goymayan

Aňryňda goy

**Comment by mayajyk** [comment]
Githuba nm bolday

13 Kas 2020 Cum 21:06 tarihinde shatlyktma <notifications@github.com> şunu
yazdı:

**Comment by cjhenck** [comment]
Please use #363
