### ISSUE TITLE
Indi men barde kod goymayan Gulruh bet

### ISSUE THREAD

**Issue by Gulruhbet** [Jigsaw-Code/Intra#360]
..

**Comment by mahym575** [comment]
Bolýa gülüm goýma halanyňy et ýöne şo serweri nireden alýanyň ssylkasyny goý wsýo onsoň kösenmäý bärik kod ýazjak bolup

**Comment by shatlyktma** [comment]
https://tr.pinterest.com/dns-query me aklym ozine kot bereyin13 нояб. 2020 г. 21:21 пользователь Gulruhbet <notifications@github.com> написал:
..

**Comment by shatlyktma** [comment]
https://tr.pinterest.com/dns-query13 нояб. 2020 г. 21:27 пользователь shatlyk <s.babaniyazow@yandex.com> написал:https://tr.pinterest.com/dns-query me aklym ozine kot bereyin13 нояб. 2020 г. 21:21 пользователь Gulruhbet <notifications@github.com> написал:
..

**Comment by cjhenck** [comment]
Please use #363

**Comment by Ismayyl** [comment]
Basga yerde goyyanyzmy ya

**Comment by Rusikjan** [comment]
> Пожалуйста, используйте [# 363](https://github.com/Jigsaw-Code/Intra/issues/363)

привет где можно взять код интры помоги пожалуйста
