### ISSUE TITLE
Kod yokmuuu

### ISSUE THREAD

**Issue by mayajyk** [Jigsaw-Code/Intra#362]
😒

**Comment by shatlyktma** [comment]
Bar13 нояб. 2020 г. 22:03 пользователь mayajyk <notifications@github.com> написал:

😒

**Comment by shatlyktma** [comment]
Sutaydan gelmez yaly edip bolanokmi sms13 нояб. 2020 г. 22:09 пользователь shatlyk <s.babaniyazow@yandex.com> написал:Bar13 нояб. 2020 г. 22:03 пользователь mayajyk <notifications@github.com> написал:

😒

**Comment by mayajyk** [comment]
Satlyk kod bera basn aylansada

**Comment by mayajyk** [comment]
Githubdan cyk gelmez son

**Comment by ALLANUR-Code** [comment]
Profilin nastroykasyna gir bar sotayda

**Comment by Ashyrmyrat** [comment]
😀

**Comment by shatlyktma** [comment]
Bada

пт, 13 нояб. 2020 г., 22:03 mayajyk <notifications@github.com>:

**Comment by shatlyktma** [comment]
Mayicka sen ucn janym gurban suny goy islar

https://kracon.anycast.censurfridns.dk/



пт, 13 нояб. 2020 г., 22:03 mayajyk <notifications@github.com>:

**Comment by suhrab1987** [comment]
https://kracon.anycast.censurfridns.dk/dns-query

**Comment by cjhenck** [comment]
Please use #363 for discussion of suggested providers
