### ISSUE TITLE
Тазе код

### ISSUE THREAD

**Issue by suhrab1987** [Jigsaw-Code/Intra#384]
https://cla.developers.google.com/dns-query

**Comment by Anonim1995** [comment]
Sag bol Suhrab! Isleýa. Kody nireden gozlap tapýanyz?

**Comment by mira1010** [comment]
Intra girya youtube achanok((((

**Comment by suhrab1987** [comment]
Ачя

**Comment by tkmli** [comment]
Salam @suhrab1987, @Anonim1995, @mira1010 

Bu ýerde kod bermeýäler. Bärde intra-nyň işgärleriniň işleýän ýeri.

Vpn gerek bolsa şu (https://twitter.com/tkm1i) ýerden bize ýazaý. Bu ýazanyňy hem 'close' basyp ýapaý.

**Comment by suhrab1987** [comment]
.
