### ISSUE TITLE
ÖMÜRLÜK isleyan kod

### ISSUE THREAD

**Issue by Gulruhbet** [Jigsaw-Code/Intra#393]
berjektim yone mira1010 Gülruh taze kod tap skkk diyenin ucin beremok..1yylyk. Kod mira1010 a sowun

**Comment by sehmus1042** [comment]
gulruhbet gayrat et mana berayde intran kodyny gayrat et teline pul gecirmeli bolsa gecirjek  ya imodan goyvar ya poctama iverayde yutuba girip bilemok o haram zadaga gulak asma o harama tuhm teji bilen musurlar bilen den bolma

**Comment by Alkascalkas** [comment]
ay bermesen berme name beyle yalvardyan adamlary. Asmandaky aymy sen. Ozumiz taparys. Licno ozum tapjak azajyk gorlayin

**Comment by sehmus1042** [comment]
mana name yazyan menden sorama mennozume kod gerek

чт, 19 нояб. 2020 г., 1:00 PM Alkascalkas <notifications@github.com>:

**Comment by Abdyreshit** [comment]
> berjektim yone mira1010 Gülruh taze kod tap skkk diyenin ucin beremok..1yylyk. Код мира1010 совун

Мана берай

**Comment by tkmli** [comment]
Salam @Gulruhbet, @sehmus1042, @Alkascalkas, @Abdyreshit 

Bu ýerde kod bermeýäler. Bärde intra-nyň işgärleriniň işleýän ýeri.

Vpn gerek bolsa şu (https://twitter.com/tkm1i) ýerden bize ýazaý. Bu ýazanyňyzy hem 'close' basyp ýapaýyň.

**Comment by sehmus1042** [comment]
mende tviter olislemeya nadip yazayin  sen men pocdama goyvaray
sehmus1042@gmail.com ya bolmasa imoda koyvaray 64746980

пт, 20 нояб. 2020 г., 4:43 PM tkmli <notifications@github.com>:

**Comment by mira1010** [comment]
Ялвармаñ тварьа кодыны готунненем анаррак соксун. Пул сорап, сизлерден мугт зады пул ишлежек боля. Пул берселер башкарак ериñам берерсин сен!!!

**Comment by mira1010** [comment]
sehmus sanada bir zat aytjak. Erkek namysyny yitirme bolor bolmaz yaly kod uchin. Kodlar iki uch gun ishleya son name yene pul tolap aljakmy koduny. Eger pulun kan bolsa "BELET VIDEO" marketdan yukleyäý et bira aya10manat 💯%

**Comment by sehmus1042** [comment]
belet vidyony yukledim mana gerek vidyony cykaranok so bar mende belet
vidio olam asta isleya

сб, 21 нояб. 2020 г., 11:37 AM Mirat <notifications@github.com>:

**Comment by Rusikjan** [comment]
> berjektim yone mira1010 Gülruh taze kod tap skkk diyenin ucin beremok..1yylyk. Код мира1010 совун

салам хайыш имо номерини язсана хайыш

**Comment by Rusikjan** [comment]
> berjektim yone mira1010 Gülruh taze kod tap skkk diyenin ucin beremok..1yylyk. Код мира1010 совун

салам хайыш телефонын номерини язсаныза имо номеринизи!!!!я-да менин имо номерим +99361983065

**Comment by Akmuhammetnurmuhammedow** [comment]
Hello

**Comment by Akmuhammetnurmuhammedow** [comment]
Hello

**Comment by Akmuhammetnurmuhammedow** [comment]
Hello

**Comment by fortuna** [comment]
Obsolete

**Comment by bayrammyradowdowletyar76-create** [comment]
https://github.com/Jigsaw-Code/Intra/issues/393#issuecomment-1920086537
