### ISSUE TITLE
Kod ýazanyň ogly bolsun

### ISSUE THREAD

**Issue by gdstar726** [Jigsaw-Code/Intra#395]

**Comment by tkmli** [comment]
Salam @gdstar726 

Bu ýerde kod bermeýäler. Bärde intra-nyň işgärleriniň işleýän ýeri.

Vpn gerek bolsa şu (https://twitter.com/tkm1i) ýerden bize ýazaý. Bu ýazanyňy hem 'close' basyp ýapaý.
