### ISSUE TITLE
Custom server URL fails

### ISSUE THREAD

**Issue by johnhtodd** [Jigsaw-Code/intra#69]
Attempting to enter a custom server URL does not permit entry.  The "OK" button never lights even after a valid https:// URL is entered (try "https://dns.quad9.net")

**Comment by cjhenck** [comment]
Thanks John - do you still see the error if you add a path to the end? (e.g. "https://dns.quad9.net/") We were trying to follow the DOH spec, which as I understand it requires a path, but perhaps we could provide better error information.  If it still doesn't work with a path we will need to investigate further.

**Comment by johnhtodd** [comment]
That's the trick.  Trailing / is required on hostname before other components like "dns-query".  Sorry for the false alarm - I was trying to test null cases and got stumped on my first attempt by the UI.

**Comment by cjhenck** [comment]
No worries, thanks for providing the feedback.  I created another issue for the user experience, I think we can do better here on the messages we provide.
