### ISSUE TITLE
Cache Query Responses

### ISSUE THREAD

**Issue by Mohammed90** [Jigsaw-Code/Intra#90]
Most of the queries are for the same hosts. Caching the result for sometime could provide significant increase in response time.

**Comment by bemasc** [comment]
Are you sure they are for the exact same host and type?  Normally I see one "A" and "AAAA" for each name.  However, I do often see a lot of queries under the same main domain, so the queries might look like the same domain if you don't expand the query details.

**Comment by Mohammed90** [comment]
Yes. Here are 2 queries for the same host and same type within about 20 seconds of each other:
- First query at 01:01:28
![image](https://user-images.githubusercontent.com/2636183/46442600-d9dae280-c772-11e8-8a55-5b5bf44e61e4.png)

- Second query at 01:01:41
![image](https://user-images.githubusercontent.com/2636183/46442635-fb3bce80-c772-11e8-943c-02e6d0b23a35.png)

**Comment by Mohammed90** [comment]
I thought I'll leave a few notes of my venture hoping it'll help whoever picks it up for implementation.

I looked at the code thinking I might implement it myself if it's very trivial (decorate the resolver somewhere). The project already uses Guava, so [Guava's Cache{Builder,Loader}](https://github.com/google/guava/wiki/CachesExplained) could fit neatly. Not so easy. The Loader requires an isolated method that returns the object to be cached. Currently I don't see any method that returns DnsTransaction. Therefore I believe a refactor is needed somewhere between DnsResolverUdpToHttps and DnsVpnService.

You're definitely more familiar with your project's code than I am, so correct my instinct if I'm wrong.

**Comment by bemasc** [comment]
It turns out that this was largely happening because of the threading bug that was fixed in #152.  With that change, the OS's built-in cache should be sufficient.
