### ISSUE TITLE
Intra doesn't seem to implement pinning nor SPKI

### ISSUE THREAD

**Issue by jedisct1** [Jigsaw-Code/Intra#99]
I don't know Java much, and Android programming even less, so maybe I have overlooked something, but it seems that Intra doesn't implement any kind of certificate pinning, nor implements any ways to do ensure that the certificate chain includes required certificates.

This is important for security, as TLS alone encrypts the communications, but doesn't ensure that the client is actually talking to the right server.

Domain names switch hands (see dnscrypt.org that is now owned by some kind of advertising company) and IP addresses get reassigned (see the recent PowerDNS case, where a DNS record they forgot about eventually ended up pointing to a malicious IP).

To mitigate this, pinning should at least be implemented. Or the client configuration should include a set of hashes, at least one of them having to match the hash of a certificate in the chain.

**Comment by bemasc** [comment]
Intra performs certificate validation using the WebPKI/CA system.  The server's domain name is its security identifier, and the client verifies the certificate chain for this name to any trusted root.  This is the standard way to validate HTTPS resources, so it's a natural fit for DNS over HTTPS, which is the protocol used by Intra.

**Comment by jedisct1** [comment]
> The server's domain name is its security identifier

Which is insufficient, and why web browsers do more (RFC7858, and now Expect-CT).
The DNS-over-TLS RFC references RFC7469, and clients even seem to have implemented it.
